version: '3'

services:
    app:
        build: .
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
        depends_on:
        - database
        ports:
        - 8080:8080
    database:
        image: postgres:15.1-alpine
        volumes:
        - db-data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
volumes:
    db-data: